### PR TITLE
Chess game

### PR DESCRIPTION
**Pull request by joewagner**
This introduces a working version of the Chess Game as an example of using the on-chain ACL features of Tableland.
It also serves as an example of how a game can leverage Tableland to both **be** and NFT and a game.

### CODE REVIEW

**Comment by joewagner** [comment]
There are a lot of changes included here.  For a high level description of what this app does look at the Updated [README](https://github.com/tablelandnetwork/example-apps/blob/8ea4b04cf3ce6311afcee1afcb86fe1561d4fe8e/chess/README.md)
Ping me with any questions or suggestions, thanks for reviewing!

**Review by carsonfarmer — APPROVED** [review]
Whoah. This is a lot of work @joewagner! I love that you embraced svelte here, super cool. Super nice to have this out there as an example.

**Comment by sanderpick** [comment]
yeah, really cool. I started a game with myself about an hour ago. somehow we should advertise this game... it's pretty slick. 

@joewagner one thing i couldn't figure out: how to set a bounty? i may have missed the opportunity when I created the game. is there a way to do that after someone makes a move?

**Comment by carsonfarmer** [comment]
I've got a tweet thread that references this demo coming out later this week... but you're right, its super cool. Perhaps we should just create a separate tweet and maybe blog post for this?

**Comment by joewagner** [comment]
Thanks for looking through this this! I'm stoked with how this worked out.  
> Perhaps we should just create a separate tweet and maybe blog post for this?

@carsonfarmer The tweet thread sounds great! I'd also be interested in writing a blog post on this if it makes sense to you?
One additional idea I had: Once we finalize this and merge, maybe we could reproduce some famous games and point to the resulting NFTs as being interesting or note worthy?  e.g. [Fisher vs. Spassky](https://www.chess.com/article/view/50-years-later-match-of-the-century-fischer-spassky).  Maybe this could concept could be worked into the tweets or blog post?

> how to set a bounty? 

@sanderpick You can set a bounty on the "home screen", where you see the list of the games you own.  It would pretty easy to add the same modal to the game screen, and could be a nice UX improvement.
One nuance of the bounty is that if the same wallet is the NFT owner and a player in the game you can't set a bounty.  I did this because the owner has complete control over indicating who the winner is, and it seemed like a conflict of interest if there is a coin bounty involved and the owner is a player.  This isn't a requirement, but the concept was that when there is a bounty involved the NFT owner becomes the "curator" of the game.  We definitely can revisit this idea if it doesn't make sense?

**Comment by sanderpick** [comment]
That makes a lot of sense. That's worth mentioning somewhere in the app (maybe I missed it).

**Review by sanderpick — APPROVED** [review]

**Comment by joewagner** [comment]
> That makes a lot of sense. That's worth mentioning somewhere in the app (maybe I missed it).

There's some comments in the code, but not any kind of explanation.  Adding some text to explain that would be easy, I can do that as well as add the bounty modal link to the game page today

**Comment by sanderpick** [comment]
Perf!

**Comment by joewagner** [comment]
I did a little more code cleanup rebased on main and added the "add bounty" link to the game page plus messaging for the bounty logic.  Gonna merge now, but there's probably still some optimizations to make.  If anyone finds any thing else let's start issues

**Pull request merged**
